# Build settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-relative-links
- jekyll-archives
relative_links:
  enable: true
  collections: true
github_username: mstile1
permalink: /:categories/:slug:output_ext
